#!/bin/bash
if [ $(uname) == Linux ]
then
	echo "PATH=~/bin:$PATH" >> ~/.bashrc
	if [ -d ~/bin ]
	then
		true
	else
		mkdir ~/bin
	fi
	wget -qO ~/bin/pmule https://raw.githubusercontent.com/Wingysam/packmule/master/pmule
	chmod +x ~/bin/pmule
else
	echo Sorry, your system is unsupported, please switch to Linux or manually install PackMule.
fi
