#!/bin/bash

echo DEPRECATED -- Installing Brew instead.

if [ $(uname) == Linux ]
then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
else
	if [ $(uname) == Darwin ]
	then
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	else
		echo "Sorry, couldn't install brew, please do it yourself."
	fi
fi
