#!/bin/bash

#Installing software
if [ $1 == install ]
then
	echo Checking if $2 exists...
	if [ $(curl -s --write-out %{http_code} "https://raw.githubusercontent.com/Wingysam/packmule/master/packages/$2" | awk 'END{print}') == 200 ]
	then
		echo Downloading...
		wget -q -O ~/Downloads/$2 https://raw.githubusercontent.com/Wingysam/packmule/master/packages/$2
		if [ "$(tail -1 ~/Downloads/$2)" == \#installerfile ]
		then
			chmod +x ~/Downloads/$2
			~/Downloads/$2
		else
			echo Copying $2 to bin.
			cp ~/Downloads/$2 ~/bin/$2
			echo Allowing running of $2 as a program.
			chmod +x ~/bin/$2
			echo $2 has been installed!
		fi
	fi
fi

#Removing software
if [ $1 == remove ]
then
	echo Checking if $2 exists...
	if [ -e ~/bin/"$2" ]
	then
		echo Removing.
		rm ~/bin/"$2"
		echo Removed.
	else
		if [ -e ~/bin/.packmuleuninstall/$2 ]
		then
			~/bin/.packmuleuninstall/$2
		fi
	fi
fi

#Updating wee
if [ $1 == update ]
then
	echo Downloading...
	wget -q -O ~/Downloads/PackMule https://raw.githubusercontent.com/Wingysam/packmule/master/pmule
	echo Creating install file...
	echo \#\/bin\/bash > ~/bin/wupd
	echo rm\ ~/bin/pmule >> ~/bin/wupd
	echo cp\ ~/Downloads/PackMule ~/bin/pmule >> ~/bin/wupd
	echo chmod +x ~/bin/pmule >> ~/bin/wupd
	echo rm\ ~/bin/wupd >> ~/bin/wupd
	chmod +x ~/bin/wupd
	echo Installing...
	wupd
	echo Updated!
fi
