#!/bin/bash

#Installing software
if [ $1 == install ]
then
	curl -s https://raw.githubusercontent.com/Wingysam/wee/master/packages/$2 > /home/$USER/404possyb
	if [ "$(</home/$USER/404possyb)" != 404\:\ Not\ Found/:\ command\ not\ found ]
	then
		wget -O /home/$USER/Downloads/$1 http://raw.githubusercontent.com/Wingysam/wee/master/packages/$1
		cp /home/$USER/Downloads/$1 /home/$USER/bin/$1
		chmod +x /home/$USER/bin/$1
	fi
	rm /home/$USER/404possyb
#	if [ $2 == run ]
#	then
#	wget -O /home/$USER/Downloads/run http://raw.githubusercontent.com/Wingysam/wee/master/run
#	cp /home/$USER/Downloads/run /home/$USER/bin/run
#	chmod +x /home/$USER/bin/run
#	fi
fi

#Removing software
if [ $1 == remove ]
then
	rm /home/$USER/bin/"$2"
fi

#Updating wee
if [ $1 == update ]
then
	wget -O /home/$USER/Downloads/wee http://raw.githubusercontent.com/Wingysam/wee/master/wee
	echo \#\/bin\/bash > /home/$USER/bin/wupd
	echo rm\ /home/$USER/bin/wee >> /home/$USER/bin/wupd
	echo cp\ /home/$USER/Downloads/wee /home/$USER/bin/wee >> /home/$USER/bin/wupd
	echo chmod +x /home/$USER/bin/wee >> /home/$USER/bin/wupd
	echo rm\ /home/$USER/bin/wupd >> /home/$USER/bin/wupd
	chmod +x /home/$USER/bin/wupd
	wupd
fi
