#!/bin/bash

#Installing software
if [ $1 == install ]
then
	echo Checking if $2 exists...
	if [ $(curl -s --write-out %{http_code} "http://raw.githubusercontent.com/Wingysam/wee/master/packages/$2" | awk 'END{print}') == 200 ]
	then
		echo Downloading...
		wget -q -O /home/$USER/Downloads/$2 http://raw.githubusercontent.com/Wingysam/wee/master/packages/$2
		echo Copying $2 to bin.
		cp /home/$USER/Downloads/$2 /home/$USER/bin/$2
		echo Allowing running of $2 as a program.
		chmod +x /home/$USER/bin/$2
		echo $2 has been installed!
	fi
fi

#Removing software
if [ $1 == remove ]
then
	echo Checking if $2 exists...
	if [ -e /home/$USER/bin/"$2" ]
	then
		echo Removing.
		rm /home/$USER/bin/"$2"
		echo Removed.
	fi
fi

#Updating wee
if [ $1 == update ]
then
	wget -O /home/$USER/Downloads/wee http://raw.githubusercontent.com/Wingysam/wee/master/wee
	echo \#\/bin\/bash > /home/$USER/bin/wupd
	echo rm\ /home/$USER/bin/wee >> /home/$USER/bin/wupd
	echo cp\ /home/$USER/Downloads/wee /home/$USER/bin/wee >> /home/$USER/bin/wupd
	echo chmod +x /home/$USER/bin/wee >> /home/$USER/bin/wupd
	echo rm\ /home/$USER/bin/wupd >> /home/$USER/bin/wupd
	chmod +x /home/$USER/bin/wupd
	wupd
fi
